export const TMDB_GENRES = [
  'Action',
  'Adventure',
  'Animation',
  'Comedy',
  'Crime',
  'Documentary',
  'Drama',
  'Family',
  'Fantasy',
  'History',
  'Horror',
  'Music',
  'Mystery',
  'Romance',
  'Science Fiction',
  'TV Movie',
  'Thriller',
  'War',
  'Western',
] as const;

export const GENRE_TRANSLATIONS: Record<string, string> = {
  'Action': 'Боевик',
  'Adventure': 'Приключения',
  'Animation': 'Анимация',
  'Comedy': 'Комедия',
  'Crime': 'Криминал',
  'Documentary': 'Документальный',
  'Drama': 'Драма',
  'Family': 'Семейный',
  'Fantasy': 'Фэнтези',
  'History': 'Исторический',
  'Horror': 'Ужасы',
  'Music': 'Музыка',
  'Mystery': 'Мистика',
  'Romance': 'Мелодрама',
  'Science Fiction': 'Научная фантастика',
  'TV Movie': 'Телефильм',
  'Thriller': 'Триллер',
  'War': 'Военный',
  'Western': 'Вестерн',
};

export const GENRE_REVERSE_TRANSLATIONS: Record<string, string> = {
  'Боевик': 'Action',
  'Приключения': 'Adventure',
  'Анимация': 'Animation',
  'Комедия': 'Comedy',
  'Криминал': 'Crime',
  'Документальный': 'Documentary',
  'Драма': 'Drama',
  'Семейный': 'Family',
  'Фэнтези': 'Fantasy',
  'Исторический': 'History',
  'Ужасы': 'Horror',
  'Музыка': 'Music',
  'Мистика': 'Mystery',
  'Мелодрама': 'Romance',
  'Научная фантастика': 'Science Fiction',
  'Телефильм': 'TV Movie',
  'Триллер': 'Thriller',
  'Военный': 'War',
  'Вестерн': 'Western',
};
